# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_app', '0002_auto_20170831_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='end_date',
            field=models.DateTimeField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travel',
            name='start_date',
            field=models.DateTimeField(default=''),
            preserve_default=False,
        ),
    ]
